packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.6.1
    '@primeuix/utils': ^0.5.3
    '@primeuix/styles': ^1.1.1
    '@primeuix/themes': ^1.1.1
    'tailwindcss-primeui': ^0.6.1
    'primeicons': ^7.0.0

catalogs:
    angular20:
        "@angular-devkit/build-angular": ^20
        "@angular/animations": ^20
        "@angular/cdk": ^20
        "@angular/cli": ^20
        "@angular/common": ^20
        "@angular/compiler": ^20
        "@angular/compiler-cli": ^20
        "@angular/core": ^20
        "@angular/forms": ^20
        "@angular/platform-browser": ^20
        "@angular/platform-browser-dynamic": ^20
        "@angular/platform-server": ^20
        "@angular/router": ^20
        "@angular/ssr": ^20
        "@angular-eslint/eslint-plugin": ^20
        "@angular-eslint/eslint-plugin-template": ^20
        "@angular-eslint/schematics": ^20
        "@angular-eslint/template-parser": ^20
        "zone.js": ~0.15.0
        "ng-packagr": ^20
        "typescript": ^5.8.2
